spring:
  application:
    name: MoAI

  datasource:
    url: jdbc:mysql://localhost:3306/moai_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET_KEY}
  # 유효시간: 3600000ms = 1시간
  expiration: 3600000